brainwaveproject/brainwaveapp/urls.py
from . import views
from django.urls import path
app_name='brainwaveapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path('portfolio',views.portfolio,name='portfolio'),
    path('service',views.service,name='service')
]

brainwaveproject/brainwaveproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from brainwaveproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('brainwaveapp.urls')),
    path('credentials/',include('credentials.urls'))
]
if settings.DEBUG:
    static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

brainwaveproject/credentials/urls.py
from . import views
from django.urls import path



urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')
]

brainwaveproject/brainwaveapp/models.py
from django.db import models

# Create your models here.

brainwaveproject/credentials/models.py
from django.db import models

# Create your models here.

brainwaveproject/brainwaveapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"index.html")
def about(request):
    return render(request,"about.html")
def contact(request):
    return render(request,"contact.html")
def portfolio(request):
    return render(request,"portfolio.html")
def service(request):
    return render(request,"service.html")

brainwaveproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        firstname=request.POST['first_name']
        lastname=request.POST['last_name']
        email=request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username):
                messages.info(request,"username is already taken")
                return redirect("register")

            elif User.objects.filter(email=email):
                messages.info(request,"Email is already taken")
                return redirect("register")
            else:
                user=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,email=email,password=password)
                user.save()
                return redirect("login")
        else:
            messages.info(request,"Password is not match")
            return redirect("register")
    return render(request,"signup.html")
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            user.save()
            return redirect("/")
        else:
            messages.info(request,"invalid credentials")
            return redirect("register")
    return render(request,"login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

brainwaveproject/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Brainwave</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <!--  Website Icon-->
  <link rel="icon" type="icon" href="{% static 'images/logos.jpg' %}">
</head>

<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'images/logos.jpg' %}" alt="" />
            <span>
              Brainwave
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mr-2">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'brainwaveapp:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:about' %}">About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:portfolio' %}">Portfolio </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:service' %}">Services</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:contact' %}">Contact us</a>
              </li>
            </ul>
            <div class="user_option">
              <div class="login_btn-container">
                <a href="">
                  Login
                </a>
              </div>
              <form class="form-inline my-2 my-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
              </form>
            </div>
          </div>
          <div class="call_btn">
            <a href="">
              Call: +91 7034232901
            </a>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->


  </div>

  <!-- custom menu -->
  <div class="custom_menu-container">
    <div class="container">
      <div class="custom_menu">
        <ul class="navbar-nav ">
          <li class="nav-item active">
                <a class="nav-link" href="{% url 'brainwaveapp:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:about' %}">About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:portfolio' %}">Portfolio </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:service' %}">Services</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:contact' %}">Contact us</a>
              </li>
        </ul>
        <div class="user_option">
          <div class="login_btn-container">
            <a href="">
              Login
            </a>
          </div>
          <form class="form-inline my-2 my-lg-0">
            <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- custom menu -->

  <!-- about section -->

  <section class="about_section layout_padding mt-5">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <div class="img-box">
            <img src="{% static 'images/about-img.png' %}" alt="" />
          </div>
        </div>
        <div class="col-md-5">
          <div class="detail-box">
            <div class="custom_heading-container">
              <h2>
                About Design
              </h2>
            </div>

            <p>
              It is a long established fact that a reader will be distracted
              by the readable content of a page when looking at its layout.
              The point of using Lorem Ipsum is that it has a more-or-less
              normal distribution of letters, as opposed to using 'Content
              here , content here', making it
            </p>
            <div>
              <a href="">
                About More
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->



  <!-- info section -->
  <section class="info_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3">
          <div class="info_links pl-lg-5">
            <h4>
              Menu
            </h4>
            <ul>
              <li>
                <a href="{% url 'brainwaveapp:index' %}">
                  Home
                </a>
              </li>
              <li class="active">
                <a href="{% url 'brainwaveapp:about' %}">
                  About
                </a>
              </li>
              <li>
                <a class="" href="{% url 'brainwaveapp:portfolio' %}">Portfolio </a>
              </li>
              <li>
                <a class="" href="{% url 'brainwaveapp:service' %}">Services</a>
              </li>
              <li>
                <a href="{% url 'brainwaveapp:contact' %} ">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="info_contact">
            <h4>
              Location
            </h4>
            <div>
              <img src="{% static 'images/location.png' %}" alt="" />
              <p>
                104 loram ipusm
              </p>
            </div>
            <div>
              <img src="{% static 'images/telephone.png' %}" alt="" />
              <p>
                ( +91 7034232901 )
              </p>
            </div>
            <div>
              <img src="{% static 'images/envelope.png' %}" alt="" />
              <p>
                hellobrainwavesolutions@gmail.com
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-lg-3">
          <div class="info_social">
            <h4>
              Social Link
            </h4>
            <div class="social_container">
              <div>
                <a href="">
                  <img src="{% static 'images/facebook-logo.png' %}" alt="" />
                </a>
              </div>
              <div>
                <a href="">
                  <img src="{% static 'images/twitter-logo.png' %}" alt="" />
                </a>
              </div>
              <div>
                <a href="">
                  <img src="{% static 'images/instagram.png' %}" alt="" />
                </a>
              </div>
              <div>
                <a href="">
                  <img src="{% static 'images/linkedin-sign.png' %}" alt="" />
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="info_form">
            <h4>
              Newsletter
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter Your Email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      &copy; 2023 All Rights Reserved By
      <a href="{% url 'brainwaveapp:index' %}">Brainwave Solutions Pvt.Ltd</a>
    </p>
  </footer>
  <!-- footer section -->

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/circles.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>

brainwaveproject/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Brainwave</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  <!--  Website Icon-->
  <link rel="icon" type="icon" href="{% static 'images/logos.jpg' %}">
</head>

<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'images/logos.jpg' %}" alt="" />
            <span>
              Brainwave
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mr-2">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'brainwaveapp:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:about' %}">About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:portfolio' %}">Portfolio </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:service' %}">Services</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:contact' %}">Contact us</a>
              </li>
            </ul>
            <div class="user_option">
              <div class="login_btn-container">
                <a href="">
                  Login
                </a>
              </div>
              <form class="form-inline my-2 my-lg-0">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
              </form>
            </div>
          </div>
          <div class="call_btn">
            <a href="">
              Call: +91 7034232901
            </a>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->


  </div>

  <!-- custom menu -->
  <div class="custom_menu-container">
    <div class="container">
      <div class="custom_menu">
        <ul class="navbar-nav ">
          <li class="nav-item active">
                <a class="nav-link" href="{% url 'brainwaveapp:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:about' %}">About </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:portfolio' %}">Portfolio </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:service' %}">Services</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'brainwaveapp:contact' %}">Contact us</a>
              </li>
        </ul>
        <div class="user_option">
          <div class="login_btn-container">
            <a href="">
              Login
            </a>
          </div>
          <form class="form-inline my-2 my-lg-0">
            <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- custom menu -->


  <!-- contact section -->

  <section class="contact_section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-4 offset-lg-2 col-md-5 offset-md-1">
          <h2 class="custom_heading">Contact Us</h2>
          <form action="#">
            <div>
              <input type="text" placeholder="Name" />
            </div>
            <div>
              <input type="email" placeholder="Email" />
            </div>
            <div>
              <input type="text" placeholder="Pone Number" />
            </div>
            <div>
              <input type="text" class="message-box" placeholder="Message" />
            </div>
            <div class="d-flex  mt-4 ">
              <button>
                SEND
              </button>
            </div>
          </form>
        </div>
        <div class="col-md-6 px-0">
          <div class="img-box">
            <img src="{% static 'images/contact.jpg' %}" alt="" class="w-100" />
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end contact section -->

  <!-- info section -->
  <section class="info_section layout_padding-top layout_padding2-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3">
          <div class="info_links pl-lg-5">
            <h4>
              Menu
            </h4>
            <ul>
              <li>
                <a href="{% url 'brainwaveapp:index' %}">
                  Home
                </a>
              </li>
              <li>
                <a href="{% url 'brainwaveapp:about' %}">
                  About
                </a>
              </li>
              <li>
                <a class="" href="{% url 'brainwaveapp:portfolio' %}">Portfolio </a>
              </li>
              <li>
                <a class="" href="{% url 'brainwaveapp:service' %}">Services</a>
              </li>
              <li class="active">
                <a href="{% url 'brainwaveapp:contact' %}">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="info_contact">
            <h4>
              Location
            </h4>
            <div>
              <img src="{% static 'images/location.png' %}" alt="" />
              <p>
                104 loram ipusm
              </p>
            </div>
            <div>
              <img src="{% static 'images/telephone.png' %}" alt="" />
              <p>
                ( +91 7034232901 )
              </p>
            </div>
            <div>
              <img src="{% static 'images/envelope.png' %}" alt="" />
              <p>
                hellobrainwavesolutions@gmail.com
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-lg-3">
          <div class="info_social">
            <h4>
              Social Link
            </h4>
            <div class="social_container">
              <div>
                <a href="">
                  <img src="{% static 'images/facebook-logo.png' %}" alt="" />
                </a>
              </div>
              <div>
                <a href="">
                  <img src="{% static 'images/twitter-logo.png' %}" alt="" />
                </a>
              </div>
              <div>
                <a href="">
                  <img src="{% static 'images/instagram.png' %}" alt="" />
                </a>
              </div>
              <div>
                <a href="">
                  <img src="{% static 'images/linkedin-sign.png' %}" alt="" />
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="info_form">
            <h4>
              Newsletter
            </h4>
            <form action="#">
              <input type="text" placeholder="Enter Your Email" />
              <button type="submit">
                Subscribe
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      &copy; 2023 All Rights Reserved By
      <a href="{% url 'brainwaveapp:index' %}">Brainwave Solutions Pvt.Ltd</a>
    </p>
  </footer>
  <!-- footer section -->

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/circles.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>

brainwaveproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/credentials.css' %}">
</head>
<body>
<form class="form" action="login" method="post">
    {% csrf_token %}
    <span class="signup">Log In</span>
    <input type="text" name="username" placeholder="Enter the username" class="form--input">
    <input type="password" name="password" placeholder="Enter password" class="form--input">

    <button class="form--submit">
        Log In
    </button>
</form>
</body>
</html>

brainwaveproject/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/credentials.css' %}">
</head>
<body>
<form class="form" action="register" method="post">
    {% csrf_token %}
    <span class="signup">Sign Up</span>
    <input type="text" name="username" placeholder="Enter the username" class="form--input">
    <input type="text" name="first_name" placeholder="Enter the first name" class="form--input">
    <input type="text" name="last_name" placeholder="Enter the last name" class="form--input">
    <input type="email" name="email" placeholder="Enter the email" class="form--input">
    <input type="password" name="password" placeholder="Enter the Password" class="form--input">
    <input type="password" name="password1" placeholder="Confirm your password" class="form--input">

    <button class="form--submit">
        Sign up
    </button>
</form>
</body>
</html>